"""
compute_stats.py — Standalone script to compute graph_stats.md from saved parquet.
Reads vertices.parquet + edges.parquet, runs pandas BFS per cascade, writes report.
"""
import os, logging, pandas as pd
from collections import deque

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

def bfs_max_depth(node_ids, edges_df):
    """BFS from the root node. Returns (max_depth, n_unreachable)."""
    adj = {}
    for _, row in edges_df.iterrows():
        adj.setdefault(row["src"], []).append(row["dst"])

    root_set = node_ids - set(edges_df["dst"].tolist())
    if not root_set:
        return 0, len(node_ids)  # no root => all disconnected

    root_id = next(iter(root_set))
    visited = {root_id: 0}
    queue = deque([root_id])
    max_d = 0
    while queue:
        node = queue.popleft()
        d = visited[node]
        for child in adj.get(node, []):
            if child not in visited:
                visited[child] = d + 1
                max_d = max(max_d, d + 1)
                queue.append(child)

    return max_d, len(node_ids - set(visited.keys()))

def main():
    out_dir = "data/processed/phase04_05_graph"
    log_dir = "logs/phase04_05_graph"
    os.makedirs(log_dir, exist_ok=True)

    logger.info("Loading vertices...")
    vertices = pd.read_parquet(f"{out_dir}/vertices.parquet")
    logger.info("  %d vertices, %d cascades", len(vertices), vertices["cascade_id"].nunique())

    logger.info("Loading edges...")
    edges = pd.read_parquet(f"{out_dir}/edges.parquet")
    logger.info("  %d edges", len(edges))

    logger.info("Running BFS per cascade...")
    rows = []
    cascade_ids = vertices["cascade_id"].unique()
    for i, cid in enumerate(cascade_ids):
        if i % 500 == 0:
            logger.info("  %d / %d ...", i, len(cascade_ids))
        v = vertices[vertices["cascade_id"] == cid]
        e = edges[edges["cascade_id"] == cid]
        node_ids = set(v["id"].tolist())
        nc = len(node_ids)
        ec = len(e)
        if ec == 0:
            rows.append({"cascade_id": cid, "node_count": nc, "edge_count": 0,
                         "is_singleton": True, "is_connected": True, "max_depth": 0, "unreachable": 0})
        else:
            md, nu = bfs_max_depth(node_ids, e)
            rows.append({"cascade_id": cid, "node_count": nc, "edge_count": ec,
                         "is_singleton": False, "is_connected": nu == 0, "max_depth": md, "unreachable": nu})

    df = pd.DataFrame(rows).sort_values("cascade_id").reset_index(drop=True)
    df.drop(columns=["unreachable"]).to_parquet(f"{out_dir}/graph_stats.parquet", index=False)

    n_total = len(df)
    n_sing = df["is_singleton"].sum()
    n_conn = df["is_connected"].sum()
    n_disc = (~df["is_connected"]).sum()
    mean_nodes = df["node_count"].mean()
    mean_edges = df["edge_count"].mean()
    mean_depth = df[df["edge_count"] > 0]["max_depth"].mean()
    max_depth = df["max_depth"].max()
    deepest = df.nlargest(5, "max_depth")[["cascade_id","max_depth","node_count","is_connected"]]

    report = f"""# CASCADE2VEC — Phase 4 Graph Stats

_Generated by compute_stats.py (pandas BFS)_

## Summary
- Total cascades: {n_total}
- Singleton cascades: {n_sing}
- Fully connected cascades: {n_conn}
- Disconnected cascades (orphaned nodes): {n_disc}
- Mean node count: {mean_nodes:.1f}
- Mean edge count: {mean_edges:.1f}
- Mean max depth (non-singleton): {mean_depth:.1f}
- Overall max depth: {max_depth}

## Top-5 Deepest Cascades
{deepest.to_markdown(index=False)}

## Per-Cascade Stats (first 20)
{df.head(20).drop(columns=["unreachable"]).to_markdown(index=False)}
"""
    with open(f"{log_dir}/graph_stats.md", "w") as f:
        f.write(report)

    print(f"\n=== RESULTS ===")
    print(f"Total cascades:        {n_total}")
    print(f"Singletons:            {n_sing}")
    print(f"Connected:             {n_conn}")
    print(f"Disconnected:          {n_disc}  (expected ~609)")
    print(f"Mean max depth:        {mean_depth:.1f}  (expected non-zero)")
    print(f"Overall max depth:     {max_depth}  (expected ~231)")
    print(f"\nTop-5 deepest:\n{deepest.to_string()}")
    print(f"\nReport: {log_dir}/graph_stats.md")

if __name__ == "__main__":
    main()
